import 'zego_super_board_error_code.dart';


extension ZegoSuperBoardErrorExtension on ZegoSuperBoardError {
  int get id {
    switch (this) {
      case ZegoSuperBoardError.success:
        return 0;
      case ZegoSuperBoardError.internal:
        return 3100001;
      case ZegoSuperBoardError.paramInvalid:
        return 3100002;
      case ZegoSuperBoardError.networkTimeout:
        return 3100003;
      case ZegoSuperBoardError.networkDisconnect:
        return 3100004;
      case ZegoSuperBoardError.response:
        return 3100005;
      case ZegoSuperBoardError.requestTooFrequent:
        return 3100006;
      case ZegoSuperBoardError.versionMismatch:
        return 3100007;
      case ZegoSuperBoardError.expressImcompatible:
        return 3100008;
      case ZegoSuperBoardError.noLoginRoom:
        return 3110001;
      case ZegoSuperBoardError.viewNotExist:
        return 3120001;
      case ZegoSuperBoardError.viewCreateFail:
        return 3120002;
      case ZegoSuperBoardError.viewModifyFail:
        return 3120003;
      case ZegoSuperBoardError.viewNameLimit:
        return 3120004;
      case ZegoSuperBoardError.viewParentNotExist:
        return 3120005;
      case ZegoSuperBoardError.viewNumLimit:
        return 3120006;
      case ZegoSuperBoardError.animationInfoLimit:
        return 3120007;
      case ZegoSuperBoardError.graphicNotExist:
        return 3130001;
      case ZegoSuperBoardError.graphicCreateFail:
        return 3130002;
      case ZegoSuperBoardError.graphicModifyFail:
        return 3130003;
      case ZegoSuperBoardError.graphicUnableDraw:
        return 3130004;
      case ZegoSuperBoardError.graphicDataLimit:
        return 3130005;
      case ZegoSuperBoardError.graphicNumLimit:
        return 3130006;
      case ZegoSuperBoardError.graphicTextLimit:
        return 3130007;
      case ZegoSuperBoardError.graphicImageSizeLimit:
        return 3130008;
      case ZegoSuperBoardError.graphicImageTypeNotSupport:
        return 3130009;
      case ZegoSuperBoardError.graphicIllegalAddress:
        return 3130010;
      case ZegoSuperBoardError.initFail:
        return 3140001;
      case ZegoSuperBoardError.getListFail:
        return 3140002;
      case ZegoSuperBoardError.createFail:
        return 3140003;
      case ZegoSuperBoardError.destroyFail:
        return 3140004;
      case ZegoSuperBoardError.attachFail:
        return 3140005;
      case ZegoSuperBoardError.clearFail:
        return 3140006;
      case ZegoSuperBoardError.scrollFail:
        return 3140007;
      case ZegoSuperBoardError.undoFail:
        return 3140008;
      case ZegoSuperBoardError.redoFail:
        return 3140009;
      case ZegoSuperBoardError.logFolderNotAccess:
        return 3140010;
      case ZegoSuperBoardError.cacheFolderNotAccess:
        return 3140011;
      case ZegoSuperBoardError.switchFail:
        return 3140012;
      case ZegoSuperBoardError.noAuthScale:
        return 3150001;
      case ZegoSuperBoardError.noAuthScroll:
        return 3150002;
      case ZegoSuperBoardError.noAuthCreateGraphic:
        return 3150003;
      case ZegoSuperBoardError.noAuthUpdateGraphic:
        return 3150004;
      case ZegoSuperBoardError.noAuthMoveGraphic:
        return 3150005;
      case ZegoSuperBoardError.noAuthDeleteGraphic:
        return 3150006;
      case ZegoSuperBoardError.noAuthClearGraphic:
        return 3150007;
      case ZegoSuperBoardError.fileNotExist:
        return 3111001;
      case ZegoSuperBoardError.uploadFailed:
        return 3111002;
      case ZegoSuperBoardError.unsupportRenderType:
        return 3111003;
      case ZegoSuperBoardError.fileEncrypt:
        return 3121001;
      case ZegoSuperBoardError.fileSizeLimit:
        return 3121002;
      case ZegoSuperBoardError.fileSheetLimit:
        return 3121003;
      case ZegoSuperBoardError.convertFail:
        return 3121004;
      case ZegoSuperBoardError.freeSpaceLimit:
        return 3131005;
      case ZegoSuperBoardError.uploadNotSupported:
        return 3131006;
      case ZegoSuperBoardError.uploadDuplicated:
        return 3131007;
      case ZegoSuperBoardError.emptyDomain:
        return 3131008;
      case ZegoSuperBoardError.duplicateInit:
        return 3131009;
      case ZegoSuperBoardError.serverFileNotExist:
        return 3131010;
      case ZegoSuperBoardError.docLogFolderNotAccess:
        return 3131011;
      case ZegoSuperBoardError.docCacheFolderNotAccess:
        return 3131012;
      case ZegoSuperBoardError.docDataFolderNotAccess:
        return 3131013;
      case ZegoSuperBoardError.cacheFailed:
        return 3131015;
      case ZegoSuperBoardError.convertCancel:
        return 3121005;
      case ZegoSuperBoardError.fileContentEmpty:
        return 3121006;
      case ZegoSuperBoardError.convertElementNotSupported:
        return 3121008;
      case ZegoSuperBoardError.convertFileTypeInvalid:
        return 3121009;
      case ZegoSuperBoardError.authParamInvalid:
        return 3131001;
      case ZegoSuperBoardError.filePathNotAccess:
        return 3131002;
      case ZegoSuperBoardError.initFailed:
        return 3131003;
      case ZegoSuperBoardError.fileReadOnly:
        return 3121007;
      case ZegoSuperBoardError.sizeInvalid:
        return 3131004;
      case ZegoSuperBoardError.graphicCursorOffsetLimit:
        return 3130011;
      case ZegoSuperBoardError.whiteboardTokenInvalid:
        return 3100010;
      case ZegoSuperBoardError.docsTokenInvalid:
        return 3100011;
      case ZegoSuperBoardError.docsSignInvalid:
        return 3100012;
      case ZegoSuperBoardError.cacheNotSupported:
        return 3131014;
      case ZegoSuperBoardError.zipFileInvalid:
        return 3131016;
      case ZegoSuperBoardError.h5FileInvalid:
        return 3131017;
    }
  }
}